# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='factura',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
