# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='fotos/productos')),
                ('valor', models.FloatField(default=0.0)),
                ('iva', models.FloatField(default=0.16)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
